### ISSUE TITLE
Invalid import in exceptions.py

### ISSUE THREAD

**Issue by jstypka** [pyelasticsearch/pyelasticsearch#177]
The import line in exceptions is:
`from urllib3.exceptions import TimeoutError as Timeout, ConnectionError`
which does not seem as a valid Python syntax. These classes are also not used in the module even though they are imported. What am I missing here?

**Comment by erikrose** [comment]
Sure, it's valid syntax. It maps TimeoutError to Timeout and imports ConnectionError verbatim. The purpose of importing them is so users of pyelasticsearch can import them from pyelasticsearch (note that they're also pulled into the top-level package namespace) rather than assuming they come from urllib3, an implementation detail. The underlying transport for pyelasticsearch may change at any time.
