### ISSUE TITLE
No way to sort queries from Elasticsearch

### ISSUE THREAD

**Issue by crccheck** [pyelasticsearch/pyelasticsearch#193]
looking at the docs https://pyelasticsearch.readthedocs.io/en/latest/api/#pyelasticsearch.ElasticSearch.search and source. There's no way to specify how to tell Elasticsearch to sort results.

For example, a full query body might be:
```
{
  "query": { "match_all": {} },
  "sort": [
    { "account_number": "asc" }
  ]
}
```
You can get `query` in, but not `sort`.

**Comment by erikrose** [comment]
`sort` can be passed as a key on the same level as `query`, as at https://github.com/mozilla/dxr/blob/master/dxr/es.py#L96. This is, as you show, exactly how the ES body syntax is designed. (IIRC, we don't take merely the inner query in the `query` kwarg because then there would be no way to send an outer `filter` key instead.)
